<?xml version="1.0" encoding="utf-8"?><Database Name="ChatbotDB" Class="ChatbotModalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ChatbotDB;Integrated Security=True" SettingsObjectName="EasySelectionChatbot.Properties.Settings" SettingsPropertyName="ChatbotDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChatbotTable$" Member="ChatbotTable_s">
    <Type Name="ChatbotTable_">
      <Column Name="monitors_no" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="measurment" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="touchscreen" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="portablity_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="feature_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="size_1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="feature_2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="feature_3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="portablity_2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[ante/intrapartum]" Member="ante_intrapartum" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="display_mode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="weights" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="feature_4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="invasive_bp" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="co2_measurment" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="nbp_measurment" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="speed" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="storage_size" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="monitors_name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>