#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySelectionChatbot
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChatbotDB")]
	public partial class ChatbotModalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ChatbotModalDataContext() : 
				base(global::EasySelectionChatbot.Properties.Settings.Default.ChatbotDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChatbotModalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatbotModalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatbotModalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatbotModalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChatbotTable_> ChatbotTable_s
		{
			get
			{
				return this.GetTable<ChatbotTable_>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChatbotTable$")]
	public partial class ChatbotTable_
	{
		
		private string _monitors_no;
		
		private string _measurment;
		
		private string _touchscreen;
		
		private string _category;
		
		private string _portablity_1;
		
		private string _feature_1;
		
		private string _size_1;
		
		private string _feature_2;
		
		private string _feature_3;
		
		private string _portablity_2;
		
		private string _ante_intrapartum;
		
		private string _display_mode;
		
		private string _weights;
		
		private string _feature_4;
		
		private string _invasive_bp;
		
		private string _co2_measurment;
		
		private string _nbp_measurment;
		
		private string _speed;
		
		private string _storage_size;
		
		private string _monitors_name;
		
		public ChatbotTable_()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitors_no", DbType="NVarChar(255)")]
		public string monitors_no
		{
			get
			{
				return this._monitors_no;
			}
			set
			{
				if ((this._monitors_no != value))
				{
					this._monitors_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_measurment", DbType="NVarChar(255)")]
		public string measurment
		{
			get
			{
				return this._measurment;
			}
			set
			{
				if ((this._measurment != value))
				{
					this._measurment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_touchscreen", DbType="NVarChar(255)")]
		public string touchscreen
		{
			get
			{
				return this._touchscreen;
			}
			set
			{
				if ((this._touchscreen != value))
				{
					this._touchscreen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(255)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portablity_1", DbType="NVarChar(255)")]
		public string portablity_1
		{
			get
			{
				return this._portablity_1;
			}
			set
			{
				if ((this._portablity_1 != value))
				{
					this._portablity_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feature_1", DbType="NVarChar(255)")]
		public string feature_1
		{
			get
			{
				return this._feature_1;
			}
			set
			{
				if ((this._feature_1 != value))
				{
					this._feature_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size_1", DbType="NVarChar(255)")]
		public string size_1
		{
			get
			{
				return this._size_1;
			}
			set
			{
				if ((this._size_1 != value))
				{
					this._size_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feature_2", DbType="NVarChar(255)")]
		public string feature_2
		{
			get
			{
				return this._feature_2;
			}
			set
			{
				if ((this._feature_2 != value))
				{
					this._feature_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feature_3", DbType="NVarChar(255)")]
		public string feature_3
		{
			get
			{
				return this._feature_3;
			}
			set
			{
				if ((this._feature_3 != value))
				{
					this._feature_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_portablity_2", DbType="NVarChar(255)")]
		public string portablity_2
		{
			get
			{
				return this._portablity_2;
			}
			set
			{
				if ((this._portablity_2 != value))
				{
					this._portablity_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ante/intrapartum]", Storage="_ante_intrapartum", DbType="NVarChar(255)")]
		public string ante_intrapartum
		{
			get
			{
				return this._ante_intrapartum;
			}
			set
			{
				if ((this._ante_intrapartum != value))
				{
					this._ante_intrapartum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_mode", DbType="NVarChar(255)")]
		public string display_mode
		{
			get
			{
				return this._display_mode;
			}
			set
			{
				if ((this._display_mode != value))
				{
					this._display_mode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weights", DbType="NVarChar(255)")]
		public string weights
		{
			get
			{
				return this._weights;
			}
			set
			{
				if ((this._weights != value))
				{
					this._weights = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feature_4", DbType="NVarChar(255)")]
		public string feature_4
		{
			get
			{
				return this._feature_4;
			}
			set
			{
				if ((this._feature_4 != value))
				{
					this._feature_4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invasive_bp", DbType="NVarChar(255)")]
		public string invasive_bp
		{
			get
			{
				return this._invasive_bp;
			}
			set
			{
				if ((this._invasive_bp != value))
				{
					this._invasive_bp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co2_measurment", DbType="NVarChar(255)")]
		public string co2_measurment
		{
			get
			{
				return this._co2_measurment;
			}
			set
			{
				if ((this._co2_measurment != value))
				{
					this._co2_measurment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbp_measurment", DbType="NVarChar(255)")]
		public string nbp_measurment
		{
			get
			{
				return this._nbp_measurment;
			}
			set
			{
				if ((this._nbp_measurment != value))
				{
					this._nbp_measurment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="NVarChar(255)")]
		public string speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storage_size", DbType="NVarChar(255)")]
		public string storage_size
		{
			get
			{
				return this._storage_size;
			}
			set
			{
				if ((this._storage_size != value))
				{
					this._storage_size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitors_name", DbType="NVarChar(255)")]
		public string monitors_name
		{
			get
			{
				return this._monitors_name;
			}
			set
			{
				if ((this._monitors_name != value))
				{
					this._monitors_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
